title: Gabriele Scrivanti's Research Page
author: Gabriele Scrivanti
url: "https://gbrscr.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "Gabriele-Scrivanti-CV.pdf"
 - name: "Contact"
   link: "contact"
