name: Insert Markdown Content

on:
  push:
    branches:
      - main  # Runs on every push to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  insert-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Insert publications.md into index.md
        run: |
          CONTENT=$(cat publications.md)  
          awk -v content="$CONTENT" '/<!-- INCLUDE-BIBLIOGRAPHY -->/ {print; print content; next}1' index.md > temp.md  
          mv temp.md index.md  

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-inserted publications.md into index.md"
          file_pattern: "index.md"
