name: Update Index with Publications

on:
  push:
    paths:
      - 'index_.md'      # Trigger if index_.md is modified
      - 'publications.md' # Trigger if publications.md is modified
    branches:
      - main  # Or your default branch name

  pull_request:
    paths:
      - 'index_.md'      # Trigger if index_.md is modified in the pull request
      - 'publications.md' # Trigger if publications.md is modified in the pull request
    branches:
      - main  # Or your default branch name

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update index file with publications
      run: |
        # Read contents of publications.md
        publications_content=$(cat publications.md)

        # Read the content of index_.md and insert publications_content at the placeholder
        index_content=$(cat index_.md)

        # Replace the placeholder <!-- publications --> with the actual content of publications.md
        updated_index_content=$(echo "$index_content" | sed "s|<!-- publications -->|$publications_content|")

        # Write the updated content to index.md
        echo "$updated_index_content" > index.md

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add index.md
        git commit -m "Update index.md with publications content"
        git push
